[project]
name = "model"
version = "0.1.0"
description = "model of butter"
requires-python = "==3.13.0"
dependencies = [
  "httpx==0.27.2",
  "httpx-ws==0.6.2",
  "loguru==0.7.2",
  "numpy==2.1.3",
  "pydantic==2.10.0",
  "pyvts==0.3.3"
]
