[project]
name = "butter"
version = "0.1.0"
description = "Butter"
authors = [
  {name = "MisileLab", email = "misile@duck.com"},
]
dependencies = [
  "tensorflow==2.17.0",
  "scipy==1.14.1",
  "scikit-learn==1.5.2",
]
requires-python = "==3.12.6"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false
