[project]
name = "model"
version = "0.1.0"
description = "model of butter"
requires-python = "==3.13.1"
dependencies = [
  "httpx==0.28.1",
  "httpx-ws==0.7.1",
  "loguru==0.7.3",
  "numpy==2.2.2",
  "pydantic==2.10.5",
  "pyvts==0.3.3"
]
