version: "0.5"

log_level: debug

processes:
  server:
    command: "cd ./backend && direnv exec . uv run fastapi run main.py --port 10002"

  frontend:
    command: "cd ./frontend && direnv exec . uv run python main.py"
    depends_on:
      server:
        condition: process_started

  client:
    command: "cd ./client && direnv exec . pnpm run preview"
    depends_on:
      server:
        condition: process_started

