[project]
name = "butter-API"
version = "0.1.0"
description = "An AI assistant"
authors = [
  {name = "MisileLaboratory", email = "misileminecord@gmail.com"},
  {name = "Landy"}
]
dependencies = [
  "tomli==2.0.1",
  "loguru==0.7.2",
  "orjson==3.10.7",
  "duckduckgo-search==6.2.11",
  "openai==1.43.0",
  "selenium==4.24.0",
  "lxml==5.3.0",
  "beautifulsoup4==4.12.3",
  "langchain-openai==0.1.23",
  "binaryornot==0.4.4",
  "mem0ai==0.1.6",
  "git+https://github.com/MisileLab/rvc-python-butter",
  "google-cloud-texttospeech==2.17.2",
  "python-multipart==0.0.9",
  "fastapi[standard]==0.112.2"
]
requires-python = "~=3.12.4"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "python-lsp-server==1.12.0",
  "ruff-lsp==0.0.55",
]

[tool.pdm.resolution.overrides]
numpy = "<2"
