[project]
name = "backend"
version = "0.1.0"
description = "Backend of butter"
requires-python = "==3.13.0"
dependencies = [
  "beautifulsoup4==4.12.3",
  "duckduckgo-search==6.3.3",
  "elevenlabs==1.12.1",
  "fastapi[standard]==0.115.4",
  "langchain-openai==0.2.4",
  "loguru==0.7.2",
  "lxml==5.3.0",
  "mem0ai==0.1.26",
  "minio==7.2.10",
  "openai==1.53.0",
  "orjson==3.10.10",
  "python-multipart==0.0.17",
  "selenium==4.26.0",
  "tomli==2.0.2",
  "websockets==13.1"
]
