[project]
name = "backend"
version = "0.1.0"
description = "Backend of butter"
requires-python = "==3.13.0"
dependencies = [
  "beautifulsoup4==4.12.3",
  "duckduckgo-search==6.3.5",
  "elevenlabs==1.12.1",
  "fastapi[standard]==0.115.5",
  "langchain-openai==0.2.8",
  "loguru==0.7.2",
  "lxml==5.3.0",
  "mem0ai==0.1.29",
  "minio==7.2.10",
  "openai==1.54.4",
  "orjson==3.10.11",
  "python-multipart==0.0.17",
  "selenium==4.26.1",
  "tomli==2.1.0",
  "websockets==14.1"
]
