[project]
name = "butter-API"
version = "0.1.0"
description = "An AI assistant"
authors = [
  {name = "MisileLaboratory", email = "misileminecord@gmail.com"},
  {name = "Landy"}
]
dependencies = [
  "tomli==2.0.2",
  "loguru==0.7.2",
  "orjson==3.10.7",
  "openai==1.52.0",
  "selenium==4.25.0",
  "lxml==5.3.0",
  "beautifulsoup4==4.12.3",
  "mem0ai==0.1.21",
  "google-cloud-texttospeech==2.18.0",
  "python-multipart==0.0.12",
  "fastapi[standard]==0.115.2",
  "pip==24.2",
  "websockets==13.1",
  "langchain-openai==0.2.3",
  "duckduckgo-search==6.3.2",
  "minio==7.2.9"
]
# numpy, httptools, uvloop
requires-python = "==3.12.5"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
  "python-lsp-server==1.12.0",
  "ruff-lsp==0.0.58",
]

[tool.pdm.resolution.overrides]
numpy = "<2"
