[project]
name = "butter-API"
version = "0.1.0"
description = "An AI assistant"
authors = [
  {name = "MisileLaboratory", email = "misileminecord@gmail.com"},
  {name = "Landy"}
]
dependencies = [
  "tomli==2.0.2",
  "loguru==0.7.2",
  "orjson==3.10.10",
  "openai==1.52.2",
  "selenium==4.25.0",
  "lxml==5.3.0",
  "beautifulsoup4==4.12.3",
  "mem0ai==0.1.23",
  "python-multipart==0.0.14",
  "fastapi[standard]==0.115.3",
  "websockets==13.1",
  "langchain-openai==0.2.3",
  "duckduckgo-search==6.3.2",
  "minio==7.2.10",
  "elevenlabs==1.10.0"
]
# numpy, httptools, uvloop
requires-python = "==3.12.6"
readme = "README.md"
license = {text = "MisileLab License"}

[tool.pdm]
distribution = false

[tool.pdm.resolution.overrides]
numpy = "<2"
