[project]
name = "backend"
version = "0.1.0"
description = "Backend of butter"
requires-python = "==3.13.1"
dependencies = [
  "beautifulsoup4==4.12.3",
  "duckduckgo-search==6.4.2",
  "elevenlabs==1.50.3",
  "fastapi[standard]==0.115.6",
  "langchain-openai==0.2.14",
  "loguru==0.7.3",
  "lxml==5.3.0",
  "mem0ai==0.1.36",
  "minio==7.2.13",
  "openai==1.58.1",
  "orjson==3.10.12",
  "python-multipart==0.0.20",
  "selenium==4.27.1",
  "tomli==2.2.1",
  "websockets==14.1"
]
